name: dtalite_pipeline
channels:
  - conda-forge
dependencies:
  - python=3.11
  - vc
  - vc14_runtime
  - vs2015_runtime
  - pandas
  - numpy
  - geopandas
  - shapely
  - fiona
  - pyproj
  - psutil
  - tqdm
  - pip
  - pip:
      - openmatrix
      - taplite4mpo-pre-release==0.4.0rc1

